server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/restaurantratingapp
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
  application:
    name: user-service